// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yakclncgvkwhugbnxngs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlha2NsbmNndmt3aHVnYm54bmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTk4NzEsImV4cCI6MjA3Mjc5NTg3MX0.YECSCjmG5qv0Y-MYmDWr3Gwe7uG9yaC0eF7MAaOj5OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});